
class Exceptions {

    void exception() {
        try {

        } catch (Exception e) {

        }
    }
}
